### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by filipsobol** [filipsobol/sonda#1]
## Present

Making sure everything is stable before the 1.0.0 release.

## Future

- [ ] **Detect more issues with the bundle**: Visually inspecting the bundle is alright, but we should warn about more common issues.
  - [ ] Show duplicated dependencies
  - [ ] Show vulnerabilities in external dependencies (`npm audit`)
  - [ ] Show deprecated external dependencies
  - [ ] Warn about circular imports
- [ ] **Observability**: Once Sonda has all the features necessary to inspect the **current** state of the bundles, it would be nice to start working on features that allow monitoring how the bundles change over time:
  - [ ] Build comparison
- [ ] **Nice-to-haves**: These things would be nice to have. I may do they if I'm in the mood.
  - [ ] Optimize source map remapping performance
- [ ] **More integrations**: Integrate with more bundlers and frameworks, so more folks can use Sonda
  - [ ] Parcel integration ([blockers](https://github.com/parcel-bundler/parcel/discussions/10026))
  - [ ] Analog.js (need research)
  - [ ] TanStack Start (need research)

**Comment by joealden** [comment]
FYI I think TanStack Start can be dropped/marked as done here, as it's now backed by vite/rsbuild, so should "just work" - perhaps with the caveat that environment API support might be needed for things to fully work as expected (see https://github.com/filipsobol/sonda/issues/194 + https://github.com/filipsobol/sonda/issues/195) - as I believe they do/will start using that for separate client/server builds.
